name: Build and Deploy Grid Tool

on:
  push:
    branches:
      - main  # oder der Branch, von dem Sie deployen wollen

# Globale Berechtigungen für alle Jobs
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Buildx einrichten
        uses: docker/setup-buildx-action@v3

      - name: Bei GitHub Container Registry anmelden
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker‑Image bauen und pushen
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile        # Pfad zur Dockerfile explizit angeben
          push: true
          tags: ghcr.io/fischimbiss/grid-tool:latest
          no-cache: true            # erzwingt einen frischen Build, ignoriert Caches

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Per SSH auf Server deployen
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/grid-tool
            docker compose pull
            docker compose up -d
